security:
  basic:
    enabled: false
env:
  profile: development
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
    # See com.fasterxml.jackson.databind.SerializationFeature
datasource:
  url: jdbc:postgresql://localhost:5432/restful-api
  username: postgres
  password: admin
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
rest:
  defaultPage: 1
  defaultSize: 2
---
spring:
  profiles: test
env:
  profile: test